language: r
script: bash _deploy.sh
cache: packages

os:
  - linux
#  - osx

addons:
  apt:
    packages:
    - sshpass

r_packages:
  - ggplot2
  - tidyr
  - dplyr
  - ranger
  - randomForestExplainer
  - knitr
  - rmarkdown
  - githubinstall

before_deploy:
  - Rscript -e "rmarkdown::render('index.Rmd', output_dir = 'docs')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local-dir: docs
  on:
    branch: master
